Repository marshmallow-code/marshmallow, pull requests merged in 2018-10, with the labels that each got.

#968 Enforce ISO8601 when deserializing date and time
  AUTHORS.rst
  CHANGELOG.rst
  marshmallow/utils.py
  tests/test_deserialization.py
  tests/test_options.py
Labels: datetime

#962 Remove from_datestring dead code from DateTime and utils
  marshmallow/fields.py
  marshmallow/utils.py
  tests/test_utils.py
Labels: datetime

#992 Raise ValueError on attribute or data_key collision
  CHANGELOG.rst
  docs/upgrading.rst
  marshmallow/schema.py
  tests/base.py
  tests/test_schema.py
Labels: backwards incompat, enhancement, feedback welcome

#990 Fix Pluck load with data_key
  marshmallow/fields.py
  tests/test_schema.py
Labels: bug

#999 Dev remove prefix Schema parameter
  CHANGELOG.rst
  docs/upgrading.rst
  marshmallow/fields.py
  marshmallow/marshalling.py
  marshmallow/schema.py
  tests/base.py
  tests/test_marshalling.py
  tests/test_schema.py
Labels: backwards incompat

#1002 Fix Date deserialization when using custom format
  CHANGELOG.rst
  marshmallow/fields.py
  tests/test_deserialization.py
Labels: bug

#849 Allow partial loading of nested fields
  AUTHORS.rst
  docs/nesting.rst
  marshmallow/fields.py
  marshmallow/marshalling.py
  marshmallow/schema.py
  tests/test_deserialization.py
Labels: backwards incompat, enhancement, needs review

#1007 Let all fields _deserialize method accept **kwargs
  marshmallow/fields.py
Labels: refactor
